### ISSUE TITLE
correct data types

### ISSUE THREAD

**Issue by gaboesquivel** [fsbahman/apidoc-swagger#23]
Hi @fsbahman, thanks so much for this module. It just saved a lot time.

I had manually correct some data types, tho
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#dataTypeFormat

Eg.
apidoc-swagger output

```
prop:
  type: float
prop2:
  type: bigint
prop3:
  type: date
```

valid OpenAPI data type and format 

```
prop:
  type: number
  format: float
prop2:
  type: integer
  format: int64
prop3:
  type: string
  format: date
```

It would be great to fix this. If I manage to have some time to work on this I'll make a PR. 
Opening the issue for now.
